# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - fullstack-app-prod

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/main_fullstack-app-prod.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.x"

      - name: Restore dependencies
        working-directory: backend
        run: dotnet restore

      - name: Build with dotnet
        working-directory: backend
        run: dotnet build --configuration Release --no-restore

      - name: Run unit tests
        working-directory: backend
        run: dotnet test --configuration Release --no-build --verbosity minimal --logger "trx;LogFileName=test-results.trx" --filter "Category!=Integration"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: backend/Api.Tests/bin/Release/net9.0/test-results.trx

      - name: Publish
        working-directory: backend/Api
        run: dotnet publish --configuration Release --no-build -o publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: backend/Api/publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./deployable

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_070B6CE6D1F04FC7B36149917E1697D6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FE6390FDE74B41F89F17AEA6FC076A0B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_109892CDE4914865825D770CE7912713 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "fullstack-app-prod"
          slot-name: "Production"
          package: ./deployable
