name: Manual E2E Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to test
        required: true
        default: staging
        type: choice
        options:
          - staging
          - production

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache Cypress
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-

      - name: Install dependencies
        working-directory: ./Frontend
        run: npm ci

      - name: Run E2E tests against ${{ github.event.inputs.environment }}
        working-directory: ./Frontend
        env:
          CYPRESS_BASE_URL: ${{ github.event.inputs.environment == 'staging' && 'https://staging.example.com' || 'https://prod.example.com' }}
        run: npm run e2e:headless

      - name: Upload Cypress test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results-${{ github.event.inputs.environment }}
          path: Frontend/cypress/videos
          retention-days: 30

      - name: Upload Cypress test screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-screenshots-${{ github.event.inputs.environment }}
          path: Frontend/cypress/screenshots
          retention-days: 30
