name: Run E2E Tests

on:
  workflow_call:
    inputs:
      continue_on_error:
        description: Whether to continue on E2E test failure
        required: false
        default: false
        type: boolean

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            playwright-${{ runner.os }}-

      - name: Install dependencies
        working-directory: ./Frontend
        run: npm ci

      - name: Install Playwright browsers
        working-directory: ./Frontend
        run: npx playwright install --with-deps

      - name: Run E2E tests
        working-directory: ./Frontend
        run: npm run e2e
        continue-on-error: ${{ inputs.continue_on_error }}

      - name: Upload E2E test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results
          path: Frontend/playwright-report/
          retention-days: 30
