name: Run E2E Tests

on:
  workflow_call:
    inputs:
      continue_on_error:
        description: Whether to continue on E2E test failure
        required: false
        default: false
        type: boolean

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache Cypress
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-

      - name: Install dependencies
        working-directory: ./Frontend
        run: npm ci

      - name: Run E2E tests
        working-directory: ./Frontend
        run: npm run e2e:headless
        continue-on-error: ${{ inputs.continue_on_error }}

      - name: Upload Cypress test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results
          path: Frontend/cypress/videos
          retention-days: 30

      - name: Upload Cypress test screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-screenshots
          path: Frontend/cypress/screenshots
          retention-days: 30
